#!/usr/bin/env bash
apt-get -y update
apt-get -y install haproxy

sudo sed -i "9i ENABLED=1" /etc/default/haproxy

echo '
frontend glackycode.tech
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 376970-web-01 100.24.238.127:80 check
    server 376970-web-02 3.90.65.141:80 check
' >> /etc/haproxy/haproxy.cfg

service haproxy restart

