#!/usr/bin/env bash
# Installing, setup HAproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 376970-web-01 34.207.237.245:80 check
   server 376970-web-02 54.198.54.255:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start