#!/usr/bin/env bash
# backing up and compressing my dbs
mysqldump --all-databases -u root --password="$1" > backup.sql
day=$(date + "%d")
month=$(date + "%m")
year=$(date + "%Y")
file_name="$day-$month-$year.tar.gz"
tar -czvf "$file_name" backup.sql
