#!/usr/bin/env bash
# Bash Script that displays 1 to 20, different messages based on specific iterations.

ct=1
while [ $ct -lt 20 ]; do
    echo "$ct"
    case $ct in
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    ((ct++))
done
